name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Set repository name for GitHub Pages
        run: |
          echo "NEXT_PUBLIC_BASE_PATH=/$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
      
      - name: Check for custom domain
        id: check_domain
        run: |
          if [ -f "./public/CNAME" ]; then
            echo "NEXT_PUBLIC_CUSTOM_DOMAIN=true" >> $GITHUB_ENV
            echo "Custom domain found in CNAME file: $(cat ./public/CNAME)"
          else
            echo "NEXT_PUBLIC_CUSTOM_DOMAIN=false" >> $GITHUB_ENV
            echo "No custom domain found, using GitHub Pages URL"
          fi
      
      - name: Build with Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
          NEXT_PUBLIC_CUSTOM_DOMAIN: ${{ env.NEXT_PUBLIC_CUSTOM_DOMAIN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      
      - name: Create .nojekyll file
        run: touch ./out/.nojekyll
        
      - name: Copy custom 404.html to output directory
        run: cp ./public/404.html ./out/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
